- name: Configuring the redis repo
  ansible.builtin.copy: 
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing mongoDB
  ansible.builtin.package:
    name: redis-6.2.13
    state: present

- name: Updating the redis config to be public  
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
      
- name: starting redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true    

- name: setting the hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}