- name: Demo on variable
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Printing value of variable
      ansible.builtin.debug:
       msg: Value of variable is {{ URL }}

    - name: Printing value of variable not declared
      ansible.builtin.debug:
       msg: Value of variable is {{ URL }}   
      vars:
        URL: tasks.google.com 