- name: installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download    

- name: cleanup of old content
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent

- name: Copying the frontend component which is downloaded on teh remote machine  
  ansible.builtin.copy:
   src: /tmp/{{ COMPONENT }}-main/static
   dest: /usr/share/nginx/html
   remote_src: yes 

- name: copy proxy configure
  ansible.builtin.copy:
   src: roboshop.conf
   dest: /etc/nginx/default.d/roboshop.conf

- name: starting nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: True      

- name: setting the hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}
      

    