- name: installing the erlang repo
  ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: configuring  the {{ COMPONENT }}
  ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing {{ COMPONENT }}
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

      
- name: starting {{ COMPONENT }}
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true    

- name: Creating {{COMPONENT}} App User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: setting the hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}