- name: Configuring the {{COMPONENT}} repo
  ansible.builtin.copy: 
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mysql-community-server
    state: present

      
- name: starting {{COMPONENT}}
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true    

- name: setting the hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}