- name: Downloading and extracting the file
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes 

- name: Performing {{ COMPONENT }} cleanup
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent
  ignore_error: yes

- name: Copying the files to the Roboshop home directory  
  ansible.builtin.copy:
   src: /tmp/{{ COMPONENT }}-main/
   dest: /home/roboshop/catalogue
   owner: "{{ APPUSER }}"
   group: "{{ APPUSER }}"
   remote_src: yes
  ignore_error: yes     