- name: Installing Python on {{COMPONENT}}-{{ENV}}
  ansible.builtin.yum:
    name:
      - python36  
      - gcc
      - python3-devel
    state: present

- name: Creating Appuser
  ansible.builtin.include_role:
    name: common
    tasks_from: createuser      

- name: Download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: download  
   
- name: Updating the UID in the {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^uid'
    line: uid = {{OUT.uid}}

- name: Updating the GID in the {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^gid'
    line: uid = {{OUT.group}}   

- name: Installing {{COMPONENT}} dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Download and extract frontend
  ansible.builtin.include_role:
    name: common
    tasks_from: config_src    
   
- name: setting the hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}        
    